accounts:
  - name: wpgw
    coins: ["20000token", "200000000stake"]
  - name: willgame
    coins: ["2000000000token", "100000000stake"]
validator:
  name: wpgw
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: willgame
  coins: ["10token", "100000stake"]

